#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'r-fxxk'

class CheckItOut < Brainfuck
  nxt 'COME ON!'
  inc 'YO!'
  prv 'HO!'
  dec 'WOW!'
  opn 'ﾁｪｹﾗｰ!'
  cls 'YEAH!'
  put 'AHA!?'
  get 'SO COOL!'
end

puts CheckItOut.new.fuck(ARGF.read)
